<?php

namespace Database\Seeders;

use App\Models\Empresa;
use Illuminate\Database\Seeder;

class EmpresasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Empresa::create([
            'logo_empresa' => 'images/empresa/PERRITO FELIZ/1654847307-paseo-perritos.jpg',
            'titulo_empresa' => 'PERRITO FELIZ',
            'descripcion_empresa' => 'MEDIANTE UN ACUERDO COMERCIAL CON LA FIRMA BRASCORP EMPEZAMOS CON LA VENTA DE ALIMENTO BALANCEADO PARA MASCOTAS EN BARILOCHE Y ZONA PATAGÓNICA.',
            'mision_empresa' => 'CONTRIBUIMOS A CREAR UN MUNDO MEJOR, AYUDANDO A AMAR Y PROTEGER A SUS MASCOTAS. BASADOS EN NUESTRO EQUIPO DE TRABAJO SOMOS SOLIDARIOS SOCIALMENTE, BRINDANDO LA MAYOR CANTIDAD DE TRABAJO POSIBLE, INNOVANDO CONSTANTEMENTE Y LOGRANDO UN PRESTIGIO QUE NOS HAGA PERDURAR EN EL TIEMPO. INVIRTIENDO E INNOVANDO EN PROYECTOS PARA AMPLIAR LA ESTRUCTURA Y SEGUIR CRECIENDO EN OTRAS CIUDADES. APORTANDO Y PARTICIPANDO SOLIDARIAMENTE PARA CREAR UNA COMUNIDAD INCLUSIVA Y EL CUIDADO DEL MEDIO AMBIENTE.',
            'vision_empresa' => 'SER UNA EMPRESA MODERNA Y SÓLIDA, LÍDER EN EL PAÍS Y CON PROYECCIÓN INTERNACIONAL. LIDERADA POR UN EQUIPO CON ACCESO A LA MÁS ALTA CALIDAD DE CAPACITACIÓN Y CON UNA MIRADA COLABORATIVA E INCLUSIVA.',
            'whatsapp_empresa' => '78824165',
            'facebook_empresa' => '@P3RRITOF3LIZ',
        ]);
        Empresa::create([
            'logo_empresa' => 'images/empresa/GATITO FELIZ/1654847447-athos.jpg',
            'titulo_empresa' => 'GATITO FELIZ',
            'descripcion_empresa' => 'EN MEDIO DE UN AÑO DE CRISIS ECONÓMICA Y RECESIÓN, NOS ARRIESGAMOS E IMPULSAMOS EL NEGOCIO CON UNA INYECCIÓN DE CAPITAL Y EN NOVIEMBRE INAUGURAMOS NUESTRO PRIMER LOCAL EN EL BARRIO DE MELIPAL.',
            'mision_empresa' => 'CONTRIBUIMOS A CREAR UN MUNDO MEJOR, AYUDANDO A AMAR Y PROTEGER A SUS MASCOTAS. BASADOS EN NUESTRO EQUIPO DE TRABAJO SOMOS SOLIDARIOS SOCIALMENTE, BRINDANDO LA MAYOR CANTIDAD DE TRABAJO POSIBLE, INNOVANDO CONSTANTEMENTE Y LOGRANDO UN PRESTIGIO QUE NOS HAGA PERDURAR EN EL TIEMPO. INVIRTIENDO E INNOVANDO EN PROYECTOS PARA AMPLIAR LA ESTRUCTURA Y SEGUIR CRECIENDO EN OTRAS CIUDADES. APORTANDO Y PARTICIPANDO SOLIDARIAMENTE PARA CREAR UNA COMUNIDAD INCLUSIVA Y EL CUIDADO DEL MEDIO AMBIENTE.',
            'vision_empresa' => 'SER UNA EMPRESA MODERNA Y SÓLIDA, LÍDER EN EL PAÍS Y CON PROYECCIÓN INTERNACIONAL. LIDERADA POR UN EQUIPO CON ACCESO A LA MÁS ALTA CALIDAD DE CAPACITACIÓN Y CON UNA MIRADA COLABORATIVA E INCLUSIVA.',
            'whatsapp_empresa' => '78824165',
            'facebook_empresa' => '@GATIT0F3LIZ',
        ]);
    }
}
